#!/bin/bash
#
#SBATCH --job-name=BX_S1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu 200000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/bbx/error_files/fprep_%A_%a_ses-1_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/bbx/error_files/fprep_%a_ses-1_err.txt


sub="sub-00${SLURM_ARRAY_TASK_ID}"
singularity exec -B /projects/niblab/bids_projects/:/home_dir /projects/niblab/bids_projects/Singularity_Containers/fmriprep.simg fmriprep /home_dir/Experiments/bbx/BIDS/ses-1 /home_dir/projects/niblab/bids_projects/Experiments/bbx/fmriprep/$sub/ses-1 \
    participant  \
    --participant-label $sub  \
    --fs-license-file /home_dir/freesurfer/license.txt \
    --fs-no-reconall \
    --nthreads 8 --n_cpus 16 \
    --bold2t1w-dof 12 \
    --longitudinal \
    --output-space template --template MNI152NLin2009cAsym \
    --debug  --ignore slicetiming \
    -w /home_dir/Experiments/bbx/fmriprep/$sub/ses-1 \
    --resource-monitor --write-graph --stop-on-first-crash